tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#341100",
        "tertiary-fixed-dim": "#ffb692",
        "surface-container-low": "#f0f4f3",
        "on-error": "#ffffff",
        "inverse-primary": "#76d6d5",
        "on-primary-fixed": "#002020",
        "inverse-on-surface": "#edf2f1",
        "secondary": "#006e20",
        "primary-fixed": "#93f2f2",
        "on-error-container": "#93000a",
        "inverse-surface": "#2c3131",
        "background": "#f6faf9",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#ebefee",
        "surface-container-high": "#e5e9e8",
        "surface-container-highest": "#dfe3e2",
        "on-background": "#181c1c",
        "on-secondary-fixed-variant": "#005316",
        "outline": "#6e7979",
        "secondary-fixed": "#93f993",
        "on-surface-variant": "#3e4949",
        "on-tertiary-container": "#fff9f7",
        "on-primary-container": "#e3fffe",
        "primary-container": "#008080",
        "tertiary-container": "#a96039",
        "on-secondary-container": "#007322",
        "surface-dim": "#d7dbda",
        "on-surface": "#181c1c",
        "error-container": "#ffdad6",
        "surface-tint": "#006a6a",
        "on-primary-fixed-variant": "#004f4f",
        "on-secondary-fixed": "#002105",
        "primary-fixed-dim": "#76d6d5",
        "tertiary-fixed": "#ffdbcb",
        "on-tertiary-fixed-variant": "#733512",
        "on-primary": "#ffffff",
        "tertiary": "#8b4823",
        "surface-bright": "#f6faf9",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "outline-variant": "#bdc9c8",
        "surface": "#f6faf9",
        "secondary-fixed-dim": "#77dc7a",
        "surface-variant": "#dfe3e2",
        "secondary-container": "#90f691",
        "primary": "#006565",
        "on-tertiary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1.75rem",
        full: "9999px",
      },
      spacing: {
        lg: "24px",
        xs: "4px",
        md: "16px",
        sm: "8px",
        margin_mobile: "16px",
        gutter: "24px",
        unit: "4px",
        container_max_width: "1280px",
        xl: "40px",
      },
      fontFamily: {
        "headline-lg": ["Manrope"],
        "title-md": ["Manrope"],
        "body-md": ["Atkinson Hyperlegible Next"],
        "label-sm": ["Manrope"],
        "display-lg": ["Manrope"],
        "body-lg": ["Atkinson Hyperlegible Next"],
        "headline-lg-mobile": ["Manrope"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "display-lg": [
          "48px",
          {
            lineHeight: "56px",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "32px", fontWeight: "600" },
        ],
      },
    },
  },
};
